### ISSUE TITLE
option to schedule at different intervals or options

### ISSUE THREAD

**Issue by uwe999** [ryanpcmcquen/obsidian-dropbox-backups#14]
great plugin, works off my iCloud vault as well.
It would be great to schedule different time intervals to not create so many backup files.
Or: have a daily backup directory but overwrite files during the day only when they change
For attachments I wouldn't mind having a single directory on dropbox where you only backup new/updated "binary" files
thanks!

**Comment by ryanpcmcquen** [comment]
Beyond the current setting to 'Exclude binary files', I'm not too interested in adding more than that. What some users have done is use something like Hazel to clean up old backups. Are you familiar with Hazel?

**Comment by uwe999** [comment]
Thanks, I'll check it out.
I guess I could directly change 
`// Every 20 minutes:
            60000 * 20));`
in the main.js for the plugin to change the interval?

**Comment by ryanpcmcquen** [comment]
Yes, you could also do that, but it would be overwritten by an update.

**Comment by cameronj86** [comment]
> Thanks, I'll check it out. I guess I could directly change `// Every 20 minutes: 60000 * 20));` in the main.js for the plugin to change the interval?

Were you able to get this to stick? I edited my code but the settings are still triggering daily:
https://imgur.com/6TCMceX
