### ISSUE TITLE
disable plugin on mobile devices

### ISSUE THREAD

**Issue by uwe999** [ryanpcmcquen/obsidian-dropbox-backups#15]
My vault is stored on iCloud and it's using a shared .obsidian settings folder.
With this plugin enabled on the PC it will also enable on the iphone app. 
When I open obsidian on the iphone I get a browser window to get dropbox permissions again.
Is there a way to ignore the plugin on mobile devices?

**Comment by ryanpcmcquen** [comment]
Since your settings are shared, not allowing the permissions on your phone would be the best way.

Is there a reason you don't want backups to happen on your phone?

**Comment by uwe999** [comment]
I rather have the backup only run on the PC  - the iPhone and iPad obsidian app share the same iCloud vault with the PC.
Not sure permission you are referring to?

**Comment by ryanpcmcquen** [comment]
When the Dropbox browser permission window opens, just 'Deny' permission.

**Comment by uwe999** [comment]
when I get the window "Aut-O-Backups would like to: Edit ... View..." and hit cancel it brings me back to the obsidian app.
But the next time I launch the app I get the same window again

**Comment by ryanpcmcquen** [comment]
Does iCloud have selective sync? You could exclude the `.obsidian` folder that way.

**Comment by uwe999** [comment]
no, it syncs everything

**Comment by ryanpcmcquen** [comment]
Hmmm, I'm not sure how this would work then. I guess we'd detect mobile and a have a setting to exclude it. Still, it's kind of weird and precarious. Most syncing services (Dropbox for instance) have ways to exclude folders, which would eliminate the need for any hacky workarounds.

**Comment by ryanpcmcquen** [comment]
Does this help?
https://apple.stackexchange.com/questions/372063/is-selective-sync-possible-with-icloud#379266

**Comment by uwe999** [comment]
thanks for looking into this, seems to apply to macOS, not iOS. I only have PC and iphone/iPad. The PC uses the iCloud app to enable the iCloud Drive but doesn't have any options:
![image](https://user-images.githubusercontent.com/19934504/145897498-8b7e7b0a-fd8b-4258-b288-87a60bc31949.png)

**Comment by uwe999** [comment]
I changed
"isDesktopOnly": true

in manifest.json and that seems to do the trick for me.
Thanks again for looking into it.

**Comment by ryanpcmcquen** [comment]
Yes, plenty of workarounds if you don't mind hacking the source. Glad you found one!
