### ISSUE TITLE
Backups triggered on app load regardless of interval?

### ISSUE THREAD

**Issue by FarSideHub** [ryanpcmcquen/obsidian-dropbox-backups#16]
In the 18 minutes after enabling this plug-in on Android, it's made 7 separate backups in Dropbox.

Is this intended? It seems a bit much to me.

**Comment by ryanpcmcquen** [comment]
No, that sounds like a bug. Unfortunately I don't have an Android device. Do they all have separate timestamps and folders?

**Comment by FarSideHub** [comment]
It looks like it to me:

![Screenshot_20211214-123506](https://user-images.githubusercontent.com/26534963/145928652-d7b339ce-3f86-4969-8d95-77040a7ea338.png)


I had some trouble giving the plug-in Dropbox permissions because apps drop out of memory unreasonably really on my part 3xl -it took four or five attempts, just in case that's a possible cause.

**Comment by ryanpcmcquen** [comment]
If you're willing, would you paste the content of `logs.txt` inside the plugin's directory here?

Make sure there's nothing sensitive in there first.

**Comment by FarSideHub** [comment]
Sure - I've just changed the vault name, though it wasn't especially sensitive.


[log] Loading Aut-O-Backups plugin ... 
[log] Attempting stored auth ... 
[debug] [Calendar] Trying to switch Moment.js global locale to en-gb, got en-gb 
[log] Dataview: Task & metadata parsing queued in %.3fs. 0 
[log] Dataview: File prefix tree built in %.3fs. 0.001 
[log] Attempting backup to: /Vault/2021/12/14/12_02_59_970 
[log] Unloading Aut-O-Backups plugin ... 
[log] Backup to /Vault/2021/12/14/12_02_59_970 complete!


It seems to have only the most recent backup logged. I suppose I might have disabled and re-enabled it if this isn't normal.

Thanks for looking into this. 
Scrolling up, I've failed to say thanks for sharing the plugin at all! Many thanks for your time!

**Comment by ryanpcmcquen** [comment]
That's strange ... would you try deleting the plugin and reinstalling it?

Nothing in the log points to an issue.

**Comment by ryanpcmcquen** [comment]
@FarSideHub will you try version 2.1.0?

**Comment by FarSideHub** [comment]
It seems to be working now!
Thank you very much indeed.
Now I just need to remember to come back and trim old ones before my free
dropbox space fills up! That's a much better problem to have than no real
backup of my vault!
