### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by AlaaYasser0210** [ryanpcmcquen/obsidian-dropbox-backups#18]
Thank you for the great plugin
I have just downloaded it on android and the cloud icon has a check sign inside it. But when I click on it, it doesn't do anything.
On dropbox the folder for backup was created but nothing inside of it also
Please help

**Comment by ryanpcmcquen** [comment]
I don't have an Android system to test on, but can you check the console logs inside of the plugin's folder?

**Comment by AlaaYasser0210** [comment]
I hope this what you mean
![Screenshot_2022-05-01-05-23-22-459_com mi android globalFileexplorer](https://user-images.githubusercontent.com/100446158/166130860-90262614-7a3c-427c-80c5-51899384f369.jpg)

**Comment by ryanpcmcquen** [comment]
Nice work! Can you share anything in `logs.txt` that does not have sensitive info?

**Comment by AlaaYasser0210** [comment]
Thank you
It only shows this
![Screenshot_2022-05-01-05-27-25-188_cn wps xiaomi abroad lite](https://user-images.githubusercontent.com/100446158/166130940-40f4b6ca-fa28-4848-8f00-84b15de2f992.jpg)

**Comment by ryanpcmcquen** [comment]
Does it take you to Dropbox to authorize the app? Do you have Dropbox installed?

**Comment by AlaaYasser0210** [comment]
> Does it take you to Dropbox to authorize the app? Do you have Dropbox installed?

This happened after i enabled the plugin. It took me to Dropbox and authorized the app. A folder was created for obsidian plugin but it doesn't have anything. I have Dropbox installed.

**Comment by ryanpcmcquen** [comment]
Thanks for debugging with me. The only other thing I can think of is installing this on a desktop computer, then copying the contents of the plugin folder on desktop into the Android plugin folder. No idea if that would help, but there could be some issue in the auth handshake for Android that doesn't happen on other platforms.

**Comment by AlaaYasser0210** [comment]
> Thanks for debugging with me. The only other thing I can think of is installing this on a desktop computer, then copying the contents of the plugin folder on desktop into the Android plugin folder. No idea if that would help, but there could be some issue in the auth handshake for Android that doesn't happen on other platforms.

Thank you. I will give it a try. Hope it helps
Thanks again

**Comment by ryanpcmcquen** [comment]
@AlaaYasser0210 did you try anything yet?

**Comment by AlaaYasser0210** [comment]
Sorry for replying late.
I don't know what happened but it works great now on onedrive 😃
Thank you so much for the awesome plugin!
