### ISSUE TITLE
Not working on Mac

### ISSUE THREAD

**Issue by Palvehelmed** [ryanpcmcquen/obsidian-dropbox-backups#19]
This extension seems not to work as expected on macOS 12.4. My `~/Dropbox/Apps/Obsidian Backups` is keep empty during the past week after I installed the extension. However, it's wired that the icon still works periodically, and changes sometimes as in the README.

**Comment by ryanpcmcquen** [comment]
I don't have a machine with Mac OS 12, could you provide some error logs?

**Comment by Palvehelmed** [comment]
I'd like to. How can I help to export logs? I'm not a developer, clearer could be helpful

**Comment by ryanpcmcquen** [comment]
You'll have to open the Developer Tools, there should be an option in one of the Obsidian menus.

**Comment by Palvehelmed** [comment]
Sorry for the late reply. It took days to understand where it is. Do you mean this? 

![image](https://user-images.githubusercontent.com/36530040/170981292-fc0e7ace-da7a-4975-9d5e-5d57daebe281.png)

Let me know if you need more info.

**Comment by ryanpcmcquen** [comment]
Dropbox is saying your uploads have a conflict. If your 'Obsidian Backups' folder is still empty, you could delete it and try again.

**Comment by ryanpcmcquen** [comment]
Closing due to no response. If deleting your auth token and renaming your old Backups folder does not work, let me know.
