### ISSUE TITLE
Plugin is not receiving the auth from Dropbox

### ISSUE THREAD

**Issue by jpsala** [ryanpcmcquen/obsidian-dropbox-backups#20]
Hey, first, thank you!!! Very nice plugin!!!
It's working fine on my pc, and it was working (I think) before on my mobile, but now when I try to authenticate, when obsidian is in focus again, after the auth in Dropbox, it stays there "connecting to Dropbox...", "Please DO NOT close this modal'"
Do you have some advice, I tried restarting my mobile, but the same...

**Comment by ryanpcmcquen** [comment]
You can check the mobile logs. What platform are you on?

**Comment by jpsala** [comment]
Thanks man! I'm on a redmi note 9 pro , android

**Comment by ryanpcmcquen** [comment]
I don't have an Android device, there are so many that it's hard to know what the issue could be. What browser does your device have?

**Comment by ryanpcmcquen** [comment]
Closed due to inactivity.
