### ISSUE TITLE
Exted to NExtcloud / WebDAV and local folders

### ISSUE THREAD

**Issue by feedhopper** [ryanpcmcquen/obsidian-dropbox-backups#21]
This is a GREAT idea. However: I do not use Dropbox but Nextcloud

Is there any chance to extend the plugins capabilities to include Nextcloud and local folders?

**Comment by ryanpcmcquen** [comment]
It'd be easiest to just fork it and write a new plugin.

**Comment by feedhopper** [comment]
Ah!

I would't know such a thing, as, sadly, I am not a programmer at all. My assumption was just that from users perspective, it would be nice to have something like "THE backup plugin"

**Comment by ryanpcmcquen** [comment]
Yeah, I can see how that would be nice, but I don't have the time to build such a thing (or a use case for it).

**Comment by feedhopper** [comment]
Fair enough. Thanks nonetheless.

**Comment by ryanpcmcquen** [comment]
Because Obsidian is local folders, finding a backup/snapshot solution for it should be pretty easy.

**Comment by feedhopper** [comment]
How would you go about? I am looking for file versioning, ideally incremental backups on windows
