### ISSUE TITLE
iOS Backup to Dropbox not starting

### ISSUE THREAD

**Issue by danandreicarp** [ryanpcmcquen/obsidian-dropbox-backups#22]
Hello,

Thank you for making this. 
I’ve just installed it and I’m trying to setup sync. I got asked by Dropbox to authorise it, which I did. 
However, in the app it’s still showing me the cloud with the line crossed through it. 
Not sure what’s wrong. 
I tried to see if I can find any logs but I didn’t see anything apart from my one note. I looked “On my phone”, under Obsidian, using my Files app. 

I have the Dropbox installed as well, if that matters. 

Any hints on what might be wrong?
Thank you!

**Comment by ryanpcmcquen** [comment]
Do you see any logs here?
`VAULT__FOLDER/.obsidian/plugins/obsidian-dropbox-backups/`

**Comment by danandreicarp** [comment]
Hello Ryan,

Thanks for getting back to me.
I don't see a .obsidian folder in here. It might be hidden?
I have the following path visible:
On My iPhone/Obsidian/<VAULT_FOLDER>/<vault_notes>

I'm on iOS 16.2

Thank you!

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by danandreicarp** [comment]
Actually, I can see the files now in Dropbox. Apparently it does back up something: for yesterday's date I have 4 folders, likely 4 separate backups.
However, in the Obsidian app, I still can't click the "Backup to Dropbox" button because it's greyed out (the cloud with the line through it). 

One additional question about this: what happens with all these subfolders? Are they automatically pruned periodically? 

Finally, is there a way to just save them to a predefined folder instead of using the timestamp? I'm asking because it would be easier for me to find the documents if I know the path beforehand.

Thanks!

**Comment by ryanpcmcquen** [comment]
Glad it is working!

The subfolders are not pruned, that is left up to the user.

Inside each subfolder the directory structure matches your vault.
