### ISSUE TITLE
What could be causing extremely slow file transfer?

### ISSUE THREAD

**Issue by toddz262** [ryanpcmcquen/obsidian-dropbox-backups#23]
Hi Ryan - I've just installed this and it seems to be kind of working, but so slowly that only a fraction of my files are transferred every few minutes. I'm getting Dropbox notifications every couple of minutes saying "You added 3 (or 9 or 2) files." With the 20-minute backup interval, it will be continually copying files and never achieve a full backup. 

I don't think have a bandwidth issue here -- I'm uploading at about 10 Mbps. I've turned off binary file uploading, though I don't have any large files.

There's no log file in .obsidian\plugins\obsidian-dropbox-backups

Any ideas?

**Comment by ryanpcmcquen** [comment]
That's strange. Is there anything interesting going on in the dev tools?

**Comment by toddz262** [comment]
I'm not sure what all to look for in dev tools, but I'm seeing a lot of these long stalled transactions in the network waterfall, and console messages saying "backup canceled"... 
![image](https://github.com/ryanpcmcquen/obsidian-dropbox-backups/assets/94217298/e4340cf3-1dcf-4fb8-a635-b9373ffa8d8f)

**Comment by ryanpcmcquen** [comment]
That appears to be a network issue. Something is stalling those Dropbox API calls. I am not able to reproduce this. What OS are you on?

**Comment by toddz262** [comment]
I'm on Windows 11 22H2, using Automatic IP & DNS assignment with a cable ISP.
I get that network issues aren't under your control, but given the consistent 45-second stalls I wondered if Dropbox was throttling the API or something. (Though Dropbox docs suggest that it's very unlikely to exceed their rate limits.)
Let me know if you'd like me to check for anything more specific...

**Comment by ryanpcmcquen** [comment]
The app has 'Production' status as a Dropbox app, which should not be rate limited. According to analytics there are over 1 million requests a day for this app and over 1500 users.

Would it be possible for you to right click one of those stalled requests, and click 'Copy as curl'? You should be able to paste that into the Windows Command Prompt and see if it takes as long in the Command Prompt.

**Comment by ryanpcmcquen** [comment]
Closed due to inactivity.
