### ISSUE TITLE
Plugin not visible in Settings -> Community plugins

### ISSUE THREAD

**Issue by merlinuwe** [ryanpcmcquen/obsidian-dropbox-backups#24]
Thanks for your great plugin.

It stores backups into the Apps folder of dropbox, as intended.

As I saw this, I asked myself, which of my plugins does this backup? Then I opened Settings -> Community plugins and could not find something with searching for "backup" or "dropbox" ...

![image](https://github.com/ryanpcmcquen/obsidian-dropbox-backups/assets/4138869/3ce03927-83ae-4cc6-a0e5-80b517cec2b8)

Could you please add it to "Community plugins" so that one can see it? (I must have installed it once manually. ;-) )

**Comment by ryanpcmcquen** [comment]
I see it here:
![2024-06-27 11_02_46-Welcome - Foo - Obsidian v1 5 3](https://github.com/ryanpcmcquen/obsidian-dropbox-backups/assets/772937/c7a8cf57-8c9c-47c3-851a-97075c314cbf)
![2024-06-27 11_02_29-Welcome - Foo - Obsidian v1 5 3](https://github.com/ryanpcmcquen/obsidian-dropbox-backups/assets/772937/825e94e7-7b8f-4bf5-b90d-81683acf9f84)
![2024-06-27 11_02_23-Welcome - Foo - Obsidian v1 5 3](https://github.com/ryanpcmcquen/obsidian-dropbox-backups/assets/772937/d176e177-9d8a-472d-9e2f-dca6cb18cc72)

**Comment by ryanpcmcquen** [comment]
Let me know if you're still not able to find it.

**Comment by merlinuwe** [comment]
Ahh..., its name is `Aut-O-Backups`. I was focused on something like `obsidian-dropbox-backups` ... sorry for this mistake. Thank you very much.

**Comment by ryanpcmcquen** [comment]
@merlinuwe, sorry for the confusion, it was originally named that, but Dropbox would not approve that name (it is against their guidelines).

**Comment by ryanpcmcquen** [comment]
https://github.com/ryanpcmcquen/obsidian-dropbox-backups?tab=readme-ov-file#what-happened-to-dropbox-backups
