### ISSUE TITLE
Question about backup efficiency

### ISSUE THREAD

**Issue by swehba** [ryanpcmcquen/obsidian-dropbox-backups#3]
It looks like the plugin does a complete backup as opposed to a partial backup. If that is true, it seems like Dropbox is almost always going to be churning away copying files given the size of a typical vault and the frequency of the backup schedule. Correct?

I just installed and enabled the plugin, and I see that it is backing up as advertised, and it is using around 10-25% CPU as well as good chunks of disk and network bandwidths.

**Comment by ryanpcmcquen** [comment]
It doesn't use that much CPU on my system ... it even runs fine on mobile. I'm guessing you have a very large vault?

**Comment by swehba** [comment]
I don't think it's particularly large. I'm also a bit confused about the number of backups that get generated. I've had the plugin enabled since I entered the question, above, which was about 9 hours ago. In that time, I now see all these time folders, each with a backup of my vault: [DropBox snapshot](https://d.pr/i/EKgE5P+).

Does it make a complete backup of my vault every few minutes? If so, I will quickly run out of DropBox space.

**Comment by ryanpcmcquen** [comment]
That looks like every 20 minutes, as advertised ... what is the disk size of your vault, and how many files does it contain?

**Comment by ryanpcmcquen** [comment]
How did you determine that just this plugin was using that much CPU? Or are you going off of the entire CPU usage of Obsidian? Do you have other plugins enabled? My whole Obsidian install, backing up my largest vault wavers around 1% CPU (often less than 1%).

I don't think there is anything to fix or address in this issue, so I'm closing it for now. Feel free to keep the discussion going, but there isn't really anything actionable here. In a future update we will look at doing batched uploads. That's not going to reduce CPU usage, in fact, it will use more CPU during the backups, but they'll go faster, so you'll have the plugin using CPU for less 'time' overall.

**Comment by ryanpcmcquen** [comment]
@swehba, depending on your vault, you may want to take advantage of the new 'Exclude binary files' setting.
