### ISSUE TITLE
Function to exclude file path from backup

### ISSUE THREAD

**Issue by chetachiezikeuzor** [ryanpcmcquen/obsidian-dropbox-backups#4]
Hello! Your plugin is absolutely wonderful! I did want to ask if file exclusion functionality was possible? If so, it would be a lovely feature to have. I have an enormous folder in my vault at the moment and I'd rather it be excluded from my backups. Thank you! 😊

**Comment by ryanpcmcquen** [comment]
We currently get all files, I suppose we could try filtering by a comma separated list of paths? Let me think about it for a bit.

**Comment by chetachiezikeuzor** [comment]
Sounds pretty complicated. Thank god I'm not doing it 🤙🏽

**Comment by ryanpcmcquen** [comment]
Hahahaha. Is the folder mainly binary assets (non-text files)?

**Comment by chetachiezikeuzor** [comment]
Yep! I have a folder full of pdfs and image files.

**Comment by ryanpcmcquen** [comment]
So maybe a better option would just be skipping binary assets (disabled by default). We already have conditionals around reading binary files, so that would be easier to implement, and it would also work better for people who store binary stuff alongside text files (which is the Obsidian default).

**Comment by ryanpcmcquen** [comment]
@chetachiezikeuzor, thoughts on the above solution?

**Comment by chetachiezikeuzor** [comment]
Sorry for the late reply but yes, this sounds like a great solution! So, say I have a backup in process that has started with skipping toggled off, if I were to then toggle it on (during the backup) would it still backup those files?

**Comment by ryanpcmcquen** [comment]
It all depends on how we code it, but I wouldn't expect it to check the config mid-backup.

**Comment by ryanpcmcquen** [comment]
@chetachiezikeuzor, landed in:
https://github.com/ryanpcmcquen/obsidian-dropbox-backups/releases/tag/1.0.0

**Comment by chetachiezikeuzor** [comment]
Woohoo! Thanks ☺️
