### ISSUE TITLE
Does this automatically prune old backups?

### ISSUE THREAD

**Issue by kerim** [ryanpcmcquen/obsidian-dropbox-backups#6]
Does this automatically prune old backups for those of us with limited Dropbox space? I'm thinking something like "keep last 10 backups" or, more complicated, "keep one backup from each month for the last 6 months, and one for each week the last 6 weeks, and one for each day the last 6 days."

**Comment by ryanpcmcquen** [comment]
Nope, that is left up to the user. The app would probably need more permissions for this and be infinitely more complex. This kind of cleanup is easily achieved with something like 'Hazel'.

**Comment by kerim** [comment]
Hazel would be easy if the file structure was flatter, but my Hazel skills aren't good enough to navigate over so many sub-folders. Do you have an example of how this could be done?

**Comment by ryanpcmcquen** [comment]
<img width="952" alt="Screen Shot 2021-06-25 at 10 23 39 PM" src="https://user-images.githubusercontent.com/772937/123502835-12e2d180-d604-11eb-8522-7bd44b434ea3.png">
<img width="960" alt="Screen Shot 2021-06-25 at 10 23 45 PM" src="https://user-images.githubusercontent.com/772937/123502837-1413fe80-d604-11eb-9397-e937abbbd034.png">
<img width="957" alt="Screen Shot 2021-06-25 at 10 23 51 PM" src="https://user-images.githubusercontent.com/772937/123502838-15452b80-d604-11eb-8143-31bbee6a8d8b.png">

**Comment by kerim** [comment]
Thanks so much!

**Comment by ryanpcmcquen** [comment]
@kerim, let me know if you find a cleaner/simpler way to write it.
