### ISSUE TITLE
Using this & git (for logseq cross-device support)

### ISSUE THREAD

**Issue by RiddheshB** [ryanpcmcquen/obsidian-dropbox-backups#8]
Apologies as I know this somewhat unrelated to the purpose of this extension (for Obsidian mobile app users)
I'm trying to get Obsidian+ Logseq working across my two PCs (already working well with dropbox)  AND mobile devices (git).
Dropbox works flawlessly, but I can't use it for mobile (logseq doesn't support it)

My obsidian, logseq vaults are already in the same dropbox folder (& I have changed obsidian settings so it saves new notes in 'pages'.)
I created a git repo in my dropbox, transferred my vaults,etc. This works well for some time- but eventually, I face sync issues, index.lock' error - which renders logseq on mobile useless

Does this extension help prevent any dropbox/ git conflicts? Or it impossible to use dropbox & git together?

**Comment by ryanpcmcquen** [comment]
I haven't tried that setup, but this plugin just makes full backups of the vault, it doesn't do syncing.

Feel free to ask more questions but I am going to close this since there is nothing actionable here.
