### ISSUE TITLE
Can not sync notes between two or more devices

### ISSUE THREAD

**Issue by congjinyebaiya** [ryanpcmcquen/obsidian-dropbox-backups#9]
# Some issues
> When i install this plugin on my PC and Android Phone at the same time and login in with dropbox account, it will create two backup files rather than sync one backup, they have same name but are not the same files (actually they are different version from two devices), which seems inconvenient.

**I hope to know if it does not have the feature that sync between multiple devices.** 

 But anyway thank you very much for your effort and contribution

**Comment by ryanpcmcquen** [comment]
No, this plugin is _only_ made for backup snapshots. I do hope to build a sync plugin as well, but that will be far more complex.
